version: '3'
services:
  mysql:
    image: 'mysql:8.1'
    hostname: 'mysql'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=hr
      - MYSQL_USER=hr
      - MYSQL_PASSWORD=secret
    ports:
      - '3306:3306'
    volumes:
        - ./mysql/data:/var/lib/mysql