version: '3'
services:
  mysql:
    image: 'mysql:8.1'
    hostname: 'mysql'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=hr
      - MYSQL_USER=hr
      - MYSQL_PASSWORD=secret
    ports:
      - '3306:3306'
  redis:
    image: "redis:latest"
    container_name: "redis"
    hostname: "redis"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    ports:
      - "6379:6379"